// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-E31umos0uq3e29Wg6CPpL0VFbVI_6yk',
    appId: '1:646859282122:web:60df27219bf33a576d4633',
    messagingSenderId: '646859282122',
    projectId: 'connectme-54fef',
    authDomain: 'connectme-54fef.firebaseapp.com',
    storageBucket: 'connectme-54fef.appspot.com',
    measurementId: 'G-YJZQD98NPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHL-ba3dB0Dm-2sMZ7DrJXYxhXoOcpdE',
    appId: '1:646859282122:android:eec1d22f344ed0026d4633',
    messagingSenderId: '646859282122',
    projectId: 'connectme-54fef',
    storageBucket: 'connectme-54fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC631JTvX-C7iEuCK2lCvStjHEtq_mIA5g',
    appId: '1:646859282122:ios:a17168ba4aee467d6d4633',
    messagingSenderId: '646859282122',
    projectId: 'connectme-54fef',
    storageBucket: 'connectme-54fef.appspot.com',
    iosBundleId: 'com.example.mingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC631JTvX-C7iEuCK2lCvStjHEtq_mIA5g',
    appId: '1:646859282122:ios:a17168ba4aee467d6d4633',
    messagingSenderId: '646859282122',
    projectId: 'connectme-54fef',
    storageBucket: 'connectme-54fef.appspot.com',
    iosBundleId: 'com.example.mingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-E31umos0uq3e29Wg6CPpL0VFbVI_6yk',
    appId: '1:646859282122:web:17ea4589dc48194c6d4633',
    messagingSenderId: '646859282122',
    projectId: 'connectme-54fef',
    authDomain: 'connectme-54fef.firebaseapp.com',
    storageBucket: 'connectme-54fef.appspot.com',
    measurementId: 'G-XZ2LEGVZXT',
  );
}
